baseURL = "http://opengeoscales.netlify.org/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "OpenGeoScales"
[markup.goldmark.renderer]
unsafe = true
